---@class Palette
---@field bg string
---@field fg string
---@field selection string
---@field comment string
---@field red string
---@field orange string
---@field yellow string
---@field green string
---@field purple string
---@field cyan string
---@field pink string
---@field bright_red string
---@field bright_green string
---@field bright_yellow string
---@field bright_blue string
---@field bright_magenta string
---@field bright_cyan string
---@field bright_white string
---@field menu string
---@field visual string
---@field gutter_fg string
---@field nontext string
---@field white string
---@field black string
return {
   bg = "#22212C",
   fg = "#F8F8F2",
   selection = "#454158",
   comment = "#7970A9",
   red = "#FF9580",
   orange = "#FFCA80",
   yellow = "#FFFF80",
   green = "#8AFF80",
   purple = "#9580FF",
   cyan = "#80FFEA",
   pink = "#FF80BF",
   bright_red = "#FF9580",
   bright_green = "#8AFF80",
   bright_yellow = "#FFFF80",
   bright_blue = "#9580FF",
   bright_magenta = "#FF80BF",
   bright_cyan = "#80FFEA",
   bright_white = "#F8F8F2",
   menu = "#11111B",
   visual = "#454158",
   gutter_fg = "#2A212C",
   nontext = "#7970A9",
   white = "#F8F8F2",
   black = "#11111B",
}
